apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - service-account.yaml
  - statefulset.yaml
  - service.yaml
  - persistentvolumeclaim.yaml
configMapGenerator:
  - name: minecraft-server-properties-configmap
    files:
      - ./server.properties
