kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minecraft-pvc
  namespace: minecraft
  labels:
    app.kubernetes.io/instance: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  volumeMode: Filesystem
